### ISSUE TITLE
DateField resetting value when no date is informed

### ISSUE THREAD

**Issue by Alvarocda** [edufolly/folly_fields#71]
With a DateField with a date set, when opening the date selection widget and closing it without informing any date, the DateField loses the value that was already set.
I think the DateField should keep the date that is set instead of leaving it empty if the user clicks cancel.

https://user-images.githubusercontent.com/12532704/154957595-cb5ee044-c2e4-4e68-aba1-89d59fb49fa0.mp4

**Comment by edufolly** [comment]
Created `clearOnCancel` attribute in `DateField`, `TimeField` and `DateTimeField`. The default value is `true` and the behavior is clear the field when the user cancel the date or times selection. Otherwise when the `clearOnCancel` attribute is changed to `false` the value of the field will not be clean.

**Comment by edufolly** [comment]
Implemented in version 0.7.6. Thanks.
